### ISSUE TITLE
win32 issues?

### ISSUE THREAD

**Issue by es128** [jonschlinkert/micromatch#17]
https://ci.appveyor.com/project/es128/chokidar

Looks like glob tests are failing on windows

**Comment by es128** [comment]
Hoping this can be resolved quickly and easily with just `s/\\/\//g` on the raw user input in a few places

**Comment by es128** [comment]
or maybe `path.posix.normalize()`

**Comment by jonschlinkert** [comment]
see:
- https://github.com/jonschlinkert/micromatch/blob/master/lib/utils.js#L5 
- https://github.com/jonschlinkert/micromatch/blob/master/lib/utils.js#L58?
- https://github.com/jonschlinkert/micromatch/blob/master/index.js#L92

just wanted to post those while I'm looking to see if I'm normalizing paths in all functions. it's possible it's only done in the main export and `.match()`

**Comment by es128** [comment]
yup remember that I'm basically just using `isMatch` so probably the same thing needs to be added there

**Comment by jonschlinkert** [comment]
was just going to say... that's it. damn, so obvious too but I don't use windows so was hard to test for that. I did actually use windows when i started on this... but now I'm on mac. guess I decided I didn't needed that on the newer methods lol.

so here we need it: https://github.com/jonschlinkert/micromatch/blob/master/index.js#L180, and...

**Comment by es128** [comment]
yeah I lost my windows vm, so I've spent the last half hour trying to set up a new one so I could start trying to help with resolution

**Comment by jonschlinkert** [comment]
the other methods like contains need it too. Okay, let's hope this fixes it. I can add those and push up a fix in a bit.

**Comment by es128** [comment]
Sounds good - I bet this is what caused the gulp-watch issue too even though they didn't mention windows

**Comment by jonschlinkert** [comment]
> so I've spent the last half hour

damn, sorry you have to go through this. I really appreciate you helping me get these kinks worked out.

**Comment by jonschlinkert** [comment]
I was thinking the exact same thing

**Comment by jonschlinkert** [comment]
ask maybe, would be good to know

**Comment by es128** [comment]
eh, I'd rather just publish the fix, confirm chokidar tests pass on appveyor, then reply over there

**Comment by jonschlinkert** [comment]
:) sounds good

**Comment by jonschlinkert** [comment]
done

**Comment by jonschlinkert** [comment]
also, fwiw looks like the benchmarks look relatively unaffected by this. the differences in the benchmarks from last run are mostly from other changes I made - overall it's matching faster than before. especially on long lists.

**Comment by es128** [comment]
:crying_cat_face:

appveyor still failing the glob tests https://ci.appveyor.com/project/es128/chokidar/branch/master/job/rewrg9yq8g2jru45

Still not set up to be able to help diagnose

**Comment by jonschlinkert** [comment]
hmm, strange. did you try dropping in minimatch to see if that fixed it? It's very possible that I'm wrong, maybe likely, but like I mentioned on the other issue it doesn't even seem related to matching. what are the patterns that are failing? I think we need to get specific

**Comment by es128** [comment]
ok, finally starting to be able to track down what's going on

```
> mm.isMatch('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\change.txt', 'C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\*a*.txt')
false
```

**Comment by jonschlinkert** [comment]
ah, that helps. right on time

**Comment by jonschlinkert** [comment]
damn windows

**Comment by es128** [comment]
srsly

**Comment by jonschlinkert** [comment]
minimatch gives the same result. 

```
micromatch:
/^(?:(%~=.)C:UsersIEUserCodechokidartest-fixtures\*a[^/]*?.txt)$/
false
false

----------

minimatch:
/^(?:(?=.)C:UsersIEUserCodechokidartest-fixtures\*a[^/]*?\.txt)$/
false
false
```

**Comment by jonschlinkert** [comment]
and regex as you can see

**Comment by es128** [comment]
doesn't seem like the backslashes are properly escaped there

**Comment by jonschlinkert** [comment]
besides that unescaped qmark dammit. yeah this is from the "fix" earlier. I know what it is

**Comment by jonschlinkert** [comment]
however, minimatch is still returning false on all of the methods, `minimatch()`, `minimatch.match()` and `minimatch.makeRe().test()`.

**Comment by es128** [comment]
yes, I'm seeing the same thing, but this definitely worked before... not sure what I'm doing/copying wrong

something about the escaping may still be messed up

**Comment by jonschlinkert** [comment]
oh, btw the paths you mentioned that's different than what I meant. I think that's just my console output. it's not actually removing slashes, just isn't showing them in the console

**Comment by jonschlinkert** [comment]
I could be wrong, I'll look at how minimatch "fixes" windows paths

**Comment by jonschlinkert** [comment]
ah, wait! what am I thinking, of course the slashes aren't there. Backslashes are disallowed in globs, in every specification, in minimatch and in micromatch.

**Comment by es128** [comment]
yes that occurred to me, but then I'm not sure why the tests worked before

**Comment by es128** [comment]
Doing stuff like [this](https://github.com/paulmillr/chokidar/blob/master/test.js#L397) is probably wrong

Still, why did it pass with minimatch? I can't even get it to work now using raw minimatch.

**Comment by es128** [comment]
How are you supposed to specify an absolute path on windows within the glob pattern? `C:/Users/**`?

**Comment by jonschlinkert** [comment]
the most likely thing is that, since the glob pattern is an absolute path, either something changed in node.js or io.js normalization of the paths, or maybe paths were relative before? I would really be kind of surprised if you were matching on absolute paths before and it worked consistently

**Comment by jonschlinkert** [comment]
that's right as far as I know

**Comment by es128** [comment]
Yes, these tests were based on absolute paths before and passed. Maybe they shouldn't have and it just worked by some odd coincidence.

**Comment by jonschlinkert** [comment]
or you're just that damn good!

**Comment by es128** [comment]
So... probably this is just an artifact of the test script... Doubt users are doing the same dumb thing

**Comment by es128** [comment]
> or you're just that damn good!

haha I think the situation is indicating toward the opposite :wink:

**Comment by jonschlinkert** [comment]
Yes, and my thinking is that it might be better (whether you use minimatch or micromatch) for you to normalize on your end to a relative, unixified path _after_ getting the absolute paths

**Comment by es128** [comment]
Do you mean normalize the glob pattern in that way? The actual fs paths need to be left alone - there's all sorts of downstream implications for users if I automatically convert them right away

**Comment by jonschlinkert** [comment]
lol nah, you're just taking a chance on a new lib that has some quarks. on the upside, sometimes it's the same with version bumps. Once you bump something and have an issue, it gets harder to tell whether it's the bumped version causing it or something else

**Comment by es128** [comment]
Anymatch allows users to provide relative or absolute paths that aren't globs as well. So I don't think unixifying all input is going to be the way to go.

Probably just need to change the tests... but I still want to figure out why it used to work

**Comment by jonschlinkert** [comment]
> So I don't think unixifying all input is going to be the way to go.

I think you meant making the paths relative, right? since we just did the unixifying here, and minimatch does it with everything so it happens anyway. 

> but I still want to figure out why it used to work

yeah I'm curious too

**Comment by es128** [comment]
> I think you meant making the paths relative, right? since we just did the unixifying here, and minimatch does it with everything so it happens anyway.

I meant that's the right place for it to happen. I don't want to convert the input prematurely in chokidar or anymatch (which I thought was what you were suggesting) because I think that'll be a rabbit hole of other implications.

**Comment by jonschlinkert** [comment]
oh, yeah got it. agreed. the main part I was focused on was relativizing paths though. It does seem like that's something that might help, given that you're already going through the trouble of getting the glob parent, etc. 

Really, you know what you're doing, it only matters that you have the correct paths, and the pattern is correctly being used against the path.

**Comment by es128** [comment]
Ok it looks to me like `minimatch` actually behaves differently on win32. Passing backslash-delimited glob patterns on darwin (as you've shown above) does not do the conversion, but on win32 it does.

Think you can easily emulate this in `micromatch`?

**Comment by es128** [comment]
```
> minimatch('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\change.txt', 'C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\*a*.txt')
true
> minimatch.makeRe('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\*a*.txt')
/^(?:C:\/Users\/IEUser\/Code\/chokidar\/test\-fixtures\/(?!\.)(?=.)[^/]*?a[^/]*?\.txt)$/
```

**Comment by jonschlinkert** [comment]
great! good find

> Think you can easily emulate this in micromatch?

Implementing it is straightforward enough, looks like minimatch just does `'a\\b\\c'.split('\\').join('/')` when win32. I'll look into it more. 

and I might be able to test on an old PC I have. But I'll have to get back to you on that, I might need someone to double check the results.

**Comment by jonschlinkert** [comment]
I'll start implementing/testing. in the meantime, if you want to try adding `glob = glob.split('\\').join('/');` after the `typeof` check in `isMatch()` to see if that fixes the issue, that would be great. no worries if you're not able to do this easily right now.

**Comment by jonschlinkert** [comment]
oh nice. thx I'll check it out.

**Comment by doowb** [comment]
@jonschlinkert fwiw I'm testing out setting up [appveyor](http://www.appveyor.com/) on a smaller project so we can start adding that to our projects. Not sure if there's a good workflow for setting up new repos and adding the badge though, but I'll let you know and do a PR here when it's ready.

**Comment by es128** [comment]
> try adding glob = glob.split('\\').join('/');

I've tried quickly sliding this in to both `isMatch()` and `matcher()` - so far no dice

**Comment by jonschlinkert** [comment]
did split have a double backslash? looks like it's normalized to one slash in the example. I did some testing on the pc here and everything is passing for me. I'll push something up in a few, and if that works we can bump and publish, if not, I'll do more digging

**Comment by jonschlinkert** [comment]
@doowb just saw your comment. thanks, that's awesome.

**Comment by es128** [comment]
The single backslash is just from the copy/paste for the comment. It does seem to fix the pattern matching, but the tests still fail... still digging around to try to figure out why.

**Comment by jonschlinkert** [comment]
Me: "I'm not going to support windows in my projects."
@doowb: "Never? c'mon"
Me: "Nope. not doin' it. Wasted too much time on windows already."
@es128: "Hey can you fix this windows problem"
Me: "Absolutely!"

why do I keep letting you back in my life windows!?

**Comment by jonschlinkert** [comment]
my tale of sorrow

**Comment by es128** [comment]
lol

**Comment by jonschlinkert** [comment]
ok, just pushed up https://github.com/jonschlinkert/micromatch/tree/fix-17. See if that does it

**Comment by es128** [comment]
There is still one test failing, but yes that seems to work. Awesome, thanks. 

Will let you know what I figure out about the failing case that remains.

**Comment by jonschlinkert** [comment]
yes, please do. thanks!

**Comment by jonschlinkert** [comment]
Let's leave this open until you know what's up with that last test

**Comment by es128** [comment]
The test is the one about ignoring the children of ignored dirs. I think my solution to that was to append `/**/*` to the dir path in the ignore patterns - so perhaps it's an issue of mixing slashes and backslashes on the pattern input.

**Comment by es128** [comment]
Well yes that's definitely what's happening, but the question is why it doesn't work

**Comment by es128** [comment]
ok here's the problem - it's actually with straight-up string matching in a matcher

```
> mm.isMatch('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\subdir', 'C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\subdir')
true
> matcher = mm.matcher('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\subdir')
[Function]
> matcher('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\subdir')
false

**Comment by jonschlinkert** [comment]
on it

**Comment by es128** [comment]
The mixed slash globstar thing is actually fine

```
> matcher = mm.matcher('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\subdir/**/*')
[Function]
> matcher('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\subdir\\foo.txt')
true
```

**Comment by jonschlinkert** [comment]
i think I know what it is

**Comment by jonschlinkert** [comment]
just to be clear, is that happening just on windows?

**Comment by es128** [comment]
seems that way

just tried on mac:
```
> mm.matcher('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\subdir')('C:\\Users\\IEUser\\Code\\chokidar\\test-fixtures\\subdir')
true
```

**Comment by jonschlinkert** [comment]
just pushed up a fix. that should do it. I even had that code in there earlier and then thought "no, this is done in the matcher". but no, it's not done in the matcher lol. really sorry for all of the time you've had to spend on this.

**Comment by es128** [comment]
I can't test it for a while, but if you go ahead and publish the patch I can trigger appveyor to go again and we can see what happens. 

Seriously, you have nothing to apologize for. This is how progress happens, and I'm happy to have participated. I can't even express how grateful I am for you and anyone else like you who looks at something like glob matching and rather than think "that's a solved problem" instead go "I can make this better". 

I am sorry that I missed an opportunity to do a better integration test before publishing and that it had an impact on users. So that's a lesson learned. But it also comes with the territory to a degree when using regularly updated OSS, so I don't feel too bad about it - it's not going to make me stop taking measured risks to try to make stuff better.

**Comment by jonschlinkert** [comment]
really awesome way to look at it, thank you for that. I'll push something up here in a little bit

**Comment by jonschlinkert** [comment]
closing per https://github.com/jonschlinkert/micromatch/commit/1f8c57383f5ac9ef9bbd233eebba3da21e209404. we can reopen or open a new issue if the need arises
